### ISSUE TITLE
logstash plugins should not trap signals

### ISSUE THREAD

**Issue by yaauie** [lliknart/logstash-input-nats#1]
https://github.com/lliknart/logstash-input-nats/blob/34cf23ce1b572510ddd63274513d287ffb37b19b/lib/logstash/inputs/nats.rb#L120

trapping `TERM` and `INT` in a Logstash plugin is considered bad-form, because these signals are used by Logstash for graceful shutdown. Binding them to a proc that calls `Kernel#exit!` is especially troublesome because that means inclusion of this plugin in one pipeline causes all pipelines to immediately and unsafely abort when receiving a signal that ordinarily would initiate a safe shutdown.

**Comment by lliknart** [comment]
#5
