### ISSUE TITLE
logstash plugins shouldn't hard-exit when they fail

### ISSUE THREAD

**Issue by yaauie** [lliknart/logstash-input-nats#2]
https://github.com/lliknart/logstash-input-nats/blob/34cf23ce1b572510ddd63274513d287ffb37b19b/lib/logstash/inputs/nats.rb#L122

changing the global error-handling of `NATS` to send `Kernel#exit!` means that any time NATS encounters an error, the entire Logstash process dies in an unsafe manner.

**Comment by lliknart** [comment]
#5
